### ISSUE TITLE
Reading and Writing Datapackages

### ISSUE THREAD

**Issue by psychemedia** [trickvi/datapackage#25]
I've just started looking over the examples of datapackages I've collected over the last few years, imagining ways I'd like to be able to work with them.

As well as being able to load a datapackage from a URL to a directory, I'd also like to be able to:

- load a datapackage from a local directory (currently broken for me in py3.4);
- load a datapackage from a gist (eg [here](https://api.github.com/gists/5633865))
- load a datapackage from a downloaded gist (.tar.gz file)
- load a datapackage from a zip archive published at a URL. (Is there an archive format/structure and suffix proposed for datapackages?)

I'd also like to be able to *write* datapackages:

- saved into a local folder;
- packaged as a zip file;
- published as a gist.

**Comment by pwalsh** [comment]
@trickvi can we close this one? The new implementation does not support gist specifically, but can do everything else IIRC ( cc @vitorbaptista )

**Comment by vitorbaptista** [comment]
Apart from the loading directly from a gist and publishing to a gist, everything else already works on https://github.com/frictionlessdata/datapackage-py.

Instead of loading from a gist URL, you can always load from the gist export file (the sample gist can be accessed [here](https://gist.github.com/psychemedia/5633865/archive/405b308b38eba8ab86f1602a3eafc9fc5beca83d.zip)). Publishing as a gist I would say is out of the scope.

I would close this and set the loading/publishing to a gist as a `wontfix`.
